/**
 * Solartis Rate API for ILT
 * To get rate for Leisure Travel from Solartis Rate API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface RatingRequestQuoteInformation {
    productID?: string;

    productVerID?: string;

    productNumber?: string;

    productVerNumber?: string;

    producerCode?: string;

    ownerId?: string;

    planName?: string;

    planCode?: string;

    departureDate?: string;

    returnDate?: string;

    depositDate?: string;

    destinationCountry?: string;

    policyEffectiveDate?: string;

    rentalStartDate?: string;

    rentalEndDate?: string;

    rentalLimit?: string;

    numberOfRentalCars?: string;

    tripCancellationCoverage?: string;

    stateCode?: string;

    quoteType?: string;

    eventName?: string;

    travelerList?: Array<models.RatingRequestQuoteInformationTravelerList>;

}
