/**
 * Solartis Policy Issuance API for ILT
 * To Policy Issuance for Leisure Travel from Solartis Rate API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface RequestPolicyInformation {
    ProductID?: string;

    ProductVerID?: string;

    ProductNumber?: string;

    ProductVerNumber?: string;

    ProducerCode?: string;

    OwnerId?: string;

    CustomerNumber?: string;

    RoleID?: string;

    RoleName?: string;

    RoleType?: string;

    EventName?: string;

    CardNumber?: string;

    CVV?: string;

    ExpiryMonth?: string;

    ExpiryYear?: string;

    PayerName?: string;

    PayerAddress1?: string;

    PayerCity?: string;

    PayerState?: string;

    PayerCountry?: string;

    PayerZipcode?: string;

    PayerEmail?: string;

    PayerPhone?: string;

    PaymentMethod?: string;

    CardType?: string;

}
