/**
 * Solartis Create Customer API for ILT
 * To create customer for Leisure Travel from Solartis Rate API.Umbrella insurance is extra liability insurance.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface RequestCustomerInformationTravelerList {
    TravelerDOB?: string;

    TravelCost?: string;

    FirstName?: string;

    LastName?: string;

    AddressLine1?: string;

    City?: string;

    State?: string;

    StateCode?: string;

    Country?: string;

    Zipcode?: string;

    Phone?: string;

    Email?: string;

    TravelerIndex?: string;

}
